-- Deliberatamente vuoto.
--
-- Il boilerplate non presume che tipo di attività lo stia usando, quindi non
-- porta con sé né un catalogo né degli utenti. Ogni installazione parte da zero:
--
--   1. Il primo utente che si registra diventa Titolare — lo fa il trigger
--      `on_auth_user_created` (vedi `app_private.handle_new_user()` nella
--      migration di baseline). Senza questa regola nessuno potrebbe creare il
--      catalogo né promuovere gli altri.
--   2. Il Titolare inserisce Categorie e Prodotti da `/catalogo`.
--
-- Un seed con utenti e password in chiaro sarebbe comodo per provare l'app dopo
-- il clone, ma in un boilerplate quelle credenziali si replicherebbero a ogni
-- nuova attività — e prima o poi una di quelle copie finisce su un progetto di
-- produzione.
--
-- Per provare il comportamento a runtime senza inserire dati a mano c'è
-- `supabase/tests/invarianti.sql`: si crea le proprie fixture e le cancella.
